version: '3.4'

services:
  darl.graphql:
    image: ${DOCKER_REGISTRY-}darlgraphql
    build:
      context: .
      dockerfile: Darl.GraphQL/Dockerfile
    restart: always
    environment:
      SINGLEUSERID: 8c663676-a7dc-4561-af3d-89b38555837d
      BLOBFILEPATH: blobs
      LOCALDATABASEPATH: database
