//using Darl.Connectivity.Models;
using Darl.GraphQL.Models.Models;
using Darl.Lineage;
using DarlCommon;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Default = Darl.GraphQL.Models.Models.Default;

namespace Darl.GraphQL.Models.Connectivity
{
    public interface IConnectivity
    {
        Task<BotModel> GetBotModel(string name);
        Task<List<BotModel>> GetBotModelsAsync();
        Task<Models.MLModel> GetMlModel(string name);
        Task<List<Models.MLModel>> GetMlModelsAsync();
        Task<Models.RuleSet> CreateEmptyRuleSet(string name);
        Task<Models.MLModel> CreateEmptyMLModel(string name);
        Task<List<UserUsage>> GetBotUsage(string appId, string v);
        Task<RuleSet> DeleteRuleSet(string name);
        Task<List<Authorization>> GetAuthorizations(string name);
        Task<Models.MLModel> DeleteMLModel(string name);
        Task<List<BotConnection>> GetBotConnectivity(string name);
        Task<RuleSet> GetRuleSet(string name);
        Task<List<RuleSet>> GetRuleSetsAsync();
        Task<BotModel> DeleteBotModel(string name);
        string userId { get; set; }
        Task<BotModel> CreateEmptyModel(string name);
        Task<List<Contact>> GetContacts();
        Task<object> CreateDefaultModel(string name);
        Task<List<Contact>> GetContactsByLastName(string lastName);
        Task<Contact> GetContactsByEmail(string email);
        Task<List<Default>> GetDefaults();
        Task<string> GetDefaultValue(string name);
        Task<Contact> CreateContactAsync(Contact contact);
        Task<Contact> UpdateContactAsync(Contact contact);
        Task<Contact> GetContactById(string Id);
        Task<Contact> DeleteContactAsync(string id);
        Task<RuleForm> CreateRuleFormFromDarl(string name, string darl);
        Task<InputFormat> UpdateRuleFormInputFormat(string name, string inputName, InputFormatUpdate inputUpdate);
        Task<OutputFormat> UpdateRuleFormOutputFormat(string ruleSetName, string outputName, OutputFormatUpdate outputUpdate);
        Task<LanguageText> UpdateRuleFormLanguageText(string ruleSetName, string languageName, string languageText);
        Task<VariantText> UpdateRuleFormVariantText(string ruleSetName, string languageName, string isoLanguageName, string variantText);
        Task<Authorization> CreateAuthorization(string name, Authorization auth);
        Task<Default> CreateUpdateDefault(string name, string value);
        Task<Default> DeleteDefault(string name);
        Task<string> DeleteAuthorization(string name, string name1);
        Task<BotConnection> CreateBotConnection(string botModelName, string appId, string password);
        Task<BotConnection> DeleteBotConnection(string botModelName, string appId);
        Task<BotInputFormat> UpdateBotModelInputFormat(string botModelName, string inputName, InputFormatUpdate inputUpdate);
        Task<BotOutputFormat> UpdateBotModelOutputFormat(string botModelName, string outputName, BotOutputFormatUpdate outputUpdate);
        Task<StringDoublePair> CreateUpdateConstant(string botModelName, string name, double value);
        Task<StringDoublePair> DeleteConstant(string botModelName, string name);
        Task<string> CreateUpdateStore(string botModelName, string name);
        Task<string> DeleteStore(string botModelName, string name);
        Task<StringStringPair> CreateUpdateString(string botModelName, string name, string value);
        Task<StringStringPair> DeleteString(string botModelName, string name);
        Task<List<LineageNodeDefinition>> GetChildrenLineageNodes(string botModelName, string path, bool isRoot);
        Task<List<LineageRecord>> GetLineagesForWord(string isoLanguage, string word);
        Task<List<LineageNodeDefinition>> GetAttribute(string botModelName, string phrase);
        Task<List<LineageNodeDefinition>> GetAttributeFromPath(string botModelName, string path);
        Task<LineageNodeAttributeUpdate> UpdateAttribute(string botModelName, LineageNodeAttributeUpdate attribute);
        Task<LineageNodeDefinition> CreateLineageNode(string botModelName, string parent, string newName);
        Task<LineageNodeDefinition> RenameLineageNode(string botModelName, string id, string newName);
        Task<LineageNodeDefinition> DeleteLineageNode(string botModelName, string id);
        Task<LineageNodeDefinition> PasteLineageNode(string botModelName, string parent, List<string> nodes, string mode);
        Task<LineageNodeDefinition> CreatePhrase(string botModelName, string path, object LineageNodeDefinition);
        Task<LineageNodeDefinition> DeletePhrase(string botModelName, string phrase);
        Task<AzureCredentials> UpdateAzureCredentials(string botModelName, string apiKey);
        Task<AzureCredentials> DeleteAzureCredentials(string botModelName);
        Task<SellerCenterCredentials> UpdateSellereCenterCredentials(string botModelName, bool liveMode, string merchantId, string stripeApiKey);
        Task<SellerCenterCredentials> DeleteSellereCenterCredentials(string botModelName);
        Task<TwilioCredentials> UpdateTwilioCredentials(string botModelName, string sMSAccountFrom, string sMSAccountIdentification, string sMSAccountPassword);
        Task<TwilioCredentials> DeleteTwilioCredentials(string botModelName);
        Task<SendGridCredentials> UpdateSendgridCredentials(string botModelName, string sendGridAPIKey);
        Task<SendGridCredentials> DeleteSendgridCredentials(string botModelName);
        Task<ZendeskCredentials> UpdateZendeskCredentials(string botModelName, string zendeskApiKey, string zendeskURL, string zendeskUser);
        Task<ZendeskCredentials> DeleteZendeskCredentials(string botModelName);
        Task<List<StringStringPair>> InferFromRulesetSimple(string ruleSetName, List<StringStringPair> inputs);
        Task<List<DarlVar>> InferFromRuleSetDarlVar(string ruleSetName, List<DarlVar> inputs);
        Task<RuleSet> CreateRuleSet(string name, RuleForm rf, ServiceConnectivity sc);
        Task<Models.MLModel> CreateMLModel(string name, DarlCommon.MLModel model);
        Task<List<DarlUser>> GetUsersByEmail(string email);
        Task<DarlUser> GetUserById(string id);
        Task<DarlUser> CreateUserAsync(DarlUserInput contact);
        Task<DarlUser> UpdateUserAsync(DarlUserUpdate darlUserUpdate);
    }
}
